apiVersion: v1
description: Apache Kafka is publish-subscribe messaging rethought as a distributed
  commit log.
name: dskafka
version: 0.4.3
keywords:
- kafka
- zookeeper
- kafka statefulset
home: https://kafka.apache.org/
sources:
- https://github.com/kubernetes/charts/tree/master/incubator/zookeeper
- https://github.com/Yolean/kubernetes-kafka
- https://github.com/confluentinc/cp-docker-images
- https://github.com/apache/kafka
icon: https://kafka.apache.org/images/logo.png
